# Generated by Django 3.0.3 on 2020-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
