# Generated by Django 3.0.3 on 2020-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_auto_20200218_1707'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='vendors',
            field=models.ManyToManyField(to='vendor.Vendor'),
        ),
    ]
